name: 'Packer GitHub Actions'
description: 'Runs Packer commands via GitHub Actions'
author: 'Kerim Satirli <kerim@operatehappy.com>'

branding: 
  color: blue
  icon: terminal

inputs: 
  actionArguments: 
    default: ''-syntax-only'
    description: 'Arguments ot append to Command'
  actionCommand: 
    default: validate
    description: 'Command to execute'
  actionTargetFile: 
    default: packer.json
    description: 'Packer files to target'
  actionVarFile: 
    description: 'JSON File containing user variables'

runs: 
  image: Dockerfile
  using: docker
