name: 'Packer GitHub Actions'
description: 'Runs Packer commands via GitHub Actions'
author: 'Kerim Satirli <kerim@operatehappy.com>'

branding: 
  color: 'blue'
  icon: 'package'

inputs: 
  version:
    description: 'Packer version to use'
    default: light
  command: 
    description: 'Command to execute'
    required: true
  arguments: 
    description: 'Arguments ot append to Command'
  varFile: 
    description: 'JSON File containing user variables'
  target: 
    default: packer.json
    description: 'Files to target'

runs: 
  using: 'docker'
  image: 'docker://hashicorp/packer:light'
  args:
    - ${{ inputs.command }}
    - ${{ inputs.arguments }}
    - "${{ inputs.target }}"
