---

name: Packer GitHub Actions
author: Kerim Satirli <kerim@operatehappy.com>
description: Runs Packer commands via GitHub Actions

inputs:
  command:
    description: Command to execute
    required: true
  arguments:
    description: Arguments to append to Command
  target:
    description: Files to target
    default: packer.json

runs:
  using: docker
  image: docker://hashicorp/packer:light
  args:
    - ${{ inputs.command }}
    - ${{ inputs.arguments }}
    - "${{ inputs.target }}"

branding:
  color: blue
  icon: package
