name: 'Packer GitHub Actions'
description: 'Runs Packer commands via GitHub Actions'
author: 'Kerim Satirli <kerim@operatehappy.com>'
branding:
  icon: 'terminal'
  color: 'blue'
inputs:
  packerCommand:
    description: 'Packer Command to execute'
    default: 'validate'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.packerCommand }}
