---

name: Packer GitHub Actions
author: Kerim Satirli <kerim@operatehappy.com>
description: Run Packer commands

inputs:
  command:
    description: command to execute
    required: true
  arguments:
    description: arguments for command
    default: -debug=false
  target:
    description: file(s) to target
    required: true
    default: artifacts.pkr.json

runs:
  using: docker
  image: docker://hashicorp/packer:light
  entrypoint: packer ${{ inputs.command }} ${{ inputs.arguments }}
  args:
    - ${{ inputs.target }}

branding:
  color: blue
  icon: package
