name: 'Packer GitHub Actions'
description: 'Runs Packer commands via GitHub Actions'
author: 'Kerim Satirli <kerim@operatehappy.com>'

branding: 
  color: 'blue'
  icon: 'package'

inputs: 
  actionCommand: 
    description: 'Command to execute'
    required: true
  actionArguments: 
    description: 'Arguments ot append to Command'
  actionVarFile: 
    description: 'JSON File containing user variables'
  actionTarget: 
    default: packer.json
    description: 'Files to target'

runs: 
  using: 'docker'
  image: 'docker://hashicorp/packer:light'
  args:
    - ${{ inputs.actionCommand }}
    - ${{ inputs.actionArguments }}
    - "-var-file=${{ inputs.actionArguments }}"
    - "${{ inputs.actionArguments }}"
